# -*- mode: ruby -*-
# vi: set ft=ruby :

node = {:hostname => "debian", :ip => "192.168.122.10", :box => "debian/bullseye64", :cpus => 4, :memory => 4096, :disk => 50}

Vagrant.configure("2") do |config|
  config.vm.box_check_update = true
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.box = node[:box]
  config.vm.hostname = node[:hostname]

  config.vm.provider "libvirt" do |libvirt|
    libvirt.management_network_address = "192.168.122.0/24" # public_network
    libvirt.cpus = node[:cpus]
    libvirt.memory = node[:memory]
    libvirt.machine_virtual_size = node[:disk]
  end

  config.vm.network :public_network,
    :dev => "virbr0",
    :mode => "bridge",
    :type => "bridge",
    :ip => node[:ip]

  config.vm.provision "shell", inline: <<-SHELL
    passwd -u root
    apt update && apt -y install curl ca-certificates
    mkdir -p /root/.ssh
    curl -sSL -o /root/.ssh/authorized_keys https://chenzhiwei.cn/keys.txt
  SHELL
end
