kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kube
networking:
  podSubnet: 6.0.0.0/8
  serviceSubnet: 7.7.0.0/16
nodes:
  - role: control-plane
    image: docker.io/kindest/node:v1.30.0
    extraMounts:
      - containerPath: /etc/containerd/certs.d
        hostPath: /etc/containerd/certs.d
  - role: worker
    image: docker.io/kindest/node:v1.30.0
    extraMounts:
      - containerPath: /etc/containerd/certs.d
        hostPath: /etc/containerd/certs.d
  - role: worker
    image: docker.io/kindest/node:v1.30.0
    extraMounts:
      - containerPath: /etc/containerd/certs.d
        hostPath: /etc/containerd/certs.d
  - role: worker
    image: docker.io/kindest/node:v1.30.0
    extraMounts:
      - containerPath: /etc/containerd/certs.d
        hostPath: /etc/containerd/certs.d
containerdConfigPatches:
  - |-
    version = 2

    [plugins."io.containerd.grpc.v1.cri".registry]
       config_path = "/etc/containerd/certs.d"
