---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-nfs
  template:
    metadata:
      labels:
        app: deployment-nfs
    spec:
      containers:
        - name: deployment-nfs
          image: docker.io/library/ubuntu:latest
          command:
            - bash
            - -c
            - set -euo pipefail; while true; do echo $(hostname) $(date) >> /mnt/outfile; sleep 5; done
          volumeMounts:
            - name: nfs
              mountPath: /mnt
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: static-nfs-pvc
